/**
* This file is used as entry point from Java. It is used to implement the native methods.
* It include de file OSApiAdapter.h which is generated by the command javac -h . OSApiAdapter in the parent folder.
*
* \file EntryPointJNI.cpp
* \author Romain Agostinelli
* \date 02.11.2020
*/
#include "MacOSNativeApiAdapter.hpp"
#include "../OSApiAdapter.h"
#include "data.h"
#include <iostream>


/**
* Implementation of: OSApiAdapter::getOsVersion.
* \return jobject, OperatingSystemVersion java object.
*/
JNIEXPORT jobject JNICALL Java_OSApiAdapter_getOsVersion
        (JNIEnv *env, jobject thisObject) 	{
    jclass cls = env->FindClass("OperatingSystemVersion");
    if(NULL == cls)
    printf("Cannot find the class");

    jmethodID cid = env->GetMethodID(cls, "<init>", "(III)V");
    if(NULL == cid)
        printf("Cannot find constructor");

    MacOSNativeApiAdapter pi;
    OSVersion version = pi.getVersion();
    return env->NewObject(cls, cid, version.major, version.minor, version.patch);
}